// File generated by FlutterFire CLI or configured manually.
// Replace the placeholder values below with your Firebase Project credentials
// from Firebase Console -> Project Settings -> General -> Your Apps.
//
// OR run the FlutterFire CLI command in your terminal:
//   npm install -g firebase-tools
//   dart pub global activate flutterfire_cli
//   flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder credentials with your actual Firebase Project credentials!

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-firebase-project-id',
    authDomain: 'your-firebase-project-id.firebaseapp.com',
    storageBucket: 'your-firebase-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
    iosBundleId: 'com.example.nexLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqpmIe3jdxBtOwfBiz7A5mZ1CTDYTbeZ0',
    appId: '1:524220896261:ios:f3fb94137ab5ba0580b86c',
    messagingSenderId: '524220896261',
    projectId: 'nexledger-9762c',
    storageBucket: 'nexledger-9762c.firebasestorage.app',
    iosBundleId: 'com.nexyra.nexLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGSBI0GJVjeYGOxC2IJQHM0KsaFEukZMM',
    appId: '1:524220896261:web:ae7b0a6a522bbf5580b86c',
    messagingSenderId: '524220896261',
    projectId: 'nexledger-9762c',
    authDomain: 'nexledger-9762c.firebaseapp.com',
    storageBucket: 'nexledger-9762c.firebasestorage.app',
    measurementId: 'G-W57X002X0B',
  );
}
